language: groovy
env:
  - GROOVY_VERSION="1.8.9"
  - GROOVY_VERSION="2.0.8"
  - GROOVY_VERSION="2.1.9"
  - GROOVY_VERSION="2.2.2"
  - GROOVY_VERSION="2.3.0"
  - GROOVY_VERSION="2.3.1"
  - GROOVY_VERSION="2.3.2"
  - GROOVY_VERSION="2.3.3"
  - GROOVY_VERSION="2.3.4"
  - GROOVY_VERSION="2.3.5"
  - GROOVY_VERSION="2.3.6"
  - GROOVY_VERSION="2.3.7"
  - GROOVY_VERSION="2.3.8"
  - GROOVY_VERSION="2.3.9"
  - GROOVY_VERSION="2.4.0-rc-1"
matrix:
  allow_failures:
    - env: GROOVY_VERSION="2.3.1"
    - env: GROOVY_VERSION="2.3.2"
    - env: GROOVY_VERSION="2.3.3"
    - env: GROOVY_VERSION="2.3.4"
    - env: GROOVY_VERSION="2.3.5"
    - env: GROOVY_VERSION="2.3.6"
    - env: GROOVY_VERSION="2.3.7"
    - env: GROOVY_VERSION="2.3.8"
    - env: GROOVY_VERSION="2.3.9"
    - env: GROOVY_VERSION="2.4.0-rc-1"
