language: groovy
env:
  - GROOVY_VERSION="1.8.9"
  - GROOVY_VERSION="2.0.8"
  - GROOVY_VERSION="2.1.9"
  - GROOVY_VERSION="2.2.2"
  - GROOVY_VERSION="2.3.9"
  - GROOVY_VERSION="2.4.0"
#gradle doesn't have a retry for assembling dependencies so here's one in bash
install: true
script: ./assemble.sh
after_success:
  - GROOVY_VERSION="1.8.9" ./gradlew cobertura coveralls
matrix:
  allow_failures:
    - env: GROOVY_VERSION="2.0.8"
    - env: GROOVY_VERSION="2.1.9"
    - env: GROOVY_VERSION="2.2.2"
    - env: GROOVY_VERSION="2.3.9"
    - env: GROOVY_VERSION="2.4.0"
